[build]
command = "npm run build"
publish = "/dist"

[functions]
directory = "public/specific_page_js"
node_bundler = "esbuild"

[context.production.environment]
VITE_DOMAIN = "https://pierpaolosestito.pythonanywhere.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200